# fly.toml app configuration file generated for white-thunder-7897 on 2023-07-09T22:07:59+03:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "white-thunder-7897"
primary_region = "ams"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
